name: build-gpdb6

on: [push, pull_request]

env:
  build_platforms: "linux/amd64,linux/arm64"

jobs:
  build_image:
    # Pin ubuntu-22.04.
    # See https://github.com/actions/runner-images/issues/11471
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        greenplum_version: ["6.27.1"]
        os_version: ["ubuntu22.04", "oraclelinux8"]
    steps:
    - uses: actions/checkout@v4

    - name: Get repo tag
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      id: vars
      run: |
        echo ::set-output name=repo_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Available platforms
      run: echo ${BUILDX_PLATFORMS}
      env:
        BUILDX_PLATFORMS: ${{ steps.buildx.outputs.platforms }}

    - name: Build greenplum image
      run: |
        docker buildx build \
          -f docker/${OS_TAG}/6/Dockerfile \
          --platform ${BUILD_PLATFORMS} \
          --build-arg GPDB_VERSION=${TAG} \
          --build-arg REPO_BUILD_TAG=${REPO_TAG} \
          -t greenplum:${TAG} .
      env: 
        TAG: ${{ matrix.greenplum_version }}
        OS_TAG: ${{ matrix.os_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}
        BUILD_PLATFORMS: ${{ env.build_platforms }}

    - name: Build image and push tag to ghcr.io and Docker Hub
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        echo ${GITHUB_PKG} | docker login ghcr.io -u ${GITHUB_USER} --password-stdin
        echo ${DOCKERHUB_PKG} | docker login -u ${DOCKERHUB_USER} --password-stdin
        docker buildx build --push \
            -f docker/${OS_TAG}/6/Dockerfile \
            --platform ${BUILD_PLATFORMS} \
            --build-arg GPDB_VERSION=${TAG} \
            --build-arg REPO_BUILD_TAG=${REPO_TAG} \
            -t ghcr.io/${GITHUB_USER}/greenplum:${TAG}-${OS_TAG} \
            -t ghcr.io/${GITHUB_USER}/greenplum:${TAG}-${OS_TAG}-${REPO_TAG} \
            -t ${DOCKERHUB_USER}/greenplum:${TAG}-${OS_TAG} \
            -t ${DOCKERHUB_USER}/greenplum:${TAG}-${OS_TAG}-${REPO_TAG} .
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_PKG: ${{ secrets.GUTHUB_CR_PAT }}
        DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
        DOCKERHUB_PKG: ${{ secrets.DOCKEHUB_TOKEN }}
        TAG: ${{ matrix.greenplum_version }}
        OS_TAG: ${{ matrix.os_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}
        BUILD_PLATFORMS: ${{ env.build_platforms }}

    - name: Push default tags (ubuntu22.04 only)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && matrix.os_version == 'ubuntu22.04'
      run: |
        echo ${GITHUB_PKG} | docker login ghcr.io -u ${GITHUB_USER} --password-stdin
        echo ${DOCKERHUB_PKG} | docker login -u ${DOCKERHUB_USER} --password-stdin
        docker buildx build --push \
             -f docker/${OS_TAG}/6/Dockerfile \
            --platform ${BUILD_PLATFORMS} \
            --build-arg GPDB_VERSION=${TAG} \
            --build-arg REPO_BUILD_TAG=${REPO_TAG} \
            -t ghcr.io/${GITHUB_USER}/greenplum:${TAG} \
            -t ghcr.io/${GITHUB_USER}/greenplum:${TAG}-${REPO_TAG} \
            -t ${DOCKERHUB_USER}/greenplum:${TAG} \
            -t ${DOCKERHUB_USER}/greenplum:${TAG}-${REPO_TAG} .
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_PKG: ${{ secrets.GUTHUB_CR_PAT }}
        DOCKERHUB_USER: ${{ secrets.DOCKEHUB_USER }}
        DOCKERHUB_PKG: ${{ secrets.DOCKEHUB_TOKEN }}
        TAG: ${{ matrix.greenplum_version }}
        OS_TAG: ${{ matrix.os_version }}
        REPO_TAG: ${{ steps.vars.outputs.repo_tag }}
        BUILD_PLATFORMS: ${{ env.build_platforms }}