services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [greenplum]
    restart: unless-stopped
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    hostname: kafka
    depends_on: [zookeeper]
    ports:
      - "19092:19092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    networks: [greenplum]
    restart: unless-stopped
    volumes:
      - kafka-data:/var/lib/kafka/data

  pyclient:
    image: python:3.11-slim
    container_name: pyclient
    hostname: pyclient
    depends_on: [kafka]
    working_dir: /workspace
    tty: true
    stdin_open: true
    ports:
      - "5001:5000"
    volumes:
      - ./addons/pyclient:/workspace
      - pyclient-pip-cache:/root/.cache/pip
    networks: [greenplum]
    restart: unless-stopped

volumes:
  zk-data:
  zk-log:
  kafka-data:
  pyclient-pip-cache:

networks:
  greenplum: {}
